[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial monitor
monitor_speed = 115200

; WiFi et HTTPClient sont inclus dans le framework ESP32, pas besoin de lib_deps

; Build type debug pour générer le .elf avec symboles (requis par Wokwi)
build_type = debug
